INSERT INTO pasatiempos (nombre) VALUES ('Leer');
INSERT INTO pasatiempos (nombre) VALUES ('Ver la tele');
INSERT INTO pasatiempos (nombre) VALUES ('Pasar tiempo con la familia');
INSERT INTO pasatiempos (nombre) VALUES ('Ir al cine');
INSERT INTO pasatiempos (nombre) VALUES ('Pescar');
INSERT INTO pasatiempos (nombre) VALUES ('Pasar el tiempo en el PC o portátil');
INSERT INTO pasatiempos (nombre) VALUES ('Dedicarse a la jardinería');
INSERT INTO pasatiempos (nombre) VALUES ('Alquilar películas');
INSERT INTO pasatiempos (nombre) VALUES ('Pasear');
INSERT INTO pasatiempos (nombre) VALUES ('Hacer ejercicio');
INSERT INTO pasatiempos (nombre) VALUES ('Escuchar música');
INSERT INTO pasatiempos (nombre) VALUES ('Realizar pequeñas tareas divertidas');
INSERT INTO pasatiempos (nombre) VALUES ('Ir de caza');
INSERT INTO pasatiempos (nombre) VALUES ('Practicar deportes en equipo');
INSERT INTO pasatiempos (nombre) VALUES ('Ir de compras');
INSERT INTO pasatiempos (nombre) VALUES ('Viajar');
INSERT INTO pasatiempos (nombre) VALUES ('Dormir');
INSERT INTO pasatiempos (nombre) VALUES ('Socializarse');
INSERT INTO pasatiempos (nombre) VALUES ('Coser');
INSERT INTO pasatiempos (nombre) VALUES ('Jugar al golf');
INSERT INTO pasatiempos (nombre) VALUES ('Actividades de iglesia');
INSERT INTO pasatiempos (nombre) VALUES ('Relajarse');
INSERT INTO pasatiempos (nombre) VALUES ('Tocar algún instrumento');
INSERT INTO pasatiempos (nombre) VALUES ('Hacer las tareas del hogar');
INSERT INTO pasatiempos (nombre) VALUES ('Artesanía');
INSERT INTO pasatiempos (nombre) VALUES ('Ver partidos');
INSERT INTO pasatiempos (nombre) VALUES ('Montar en bici');
INSERT INTO pasatiempos (nombre) VALUES ('Jugar a las cartas');
INSERT INTO pasatiempos (nombre) VALUES ('Excursionismo');
INSERT INTO pasatiempos (nombre) VALUES ('Cocinar');
INSERT INTO pasatiempos (nombre) VALUES ('Ir a cenar fuera');
INSERT INTO pasatiempos (nombre) VALUES ('Tener citas online');
INSERT INTO pasatiempos (nombre) VALUES ('Nadar');
INSERT INTO pasatiempos (nombre) VALUES ('Ir de camping');
INSERT INTO pasatiempos (nombre) VALUES ('Esquiar');
INSERT INTO pasatiempos (nombre) VALUES ('Arreglar coches');
INSERT INTO pasatiempos (nombre) VALUES ('Montar en barco');
INSERT INTO pasatiempos (nombre) VALUES ('Escribir');
INSERT INTO pasatiempos (nombre) VALUES ('Ir en motocicleta');
INSERT INTO pasatiempos (nombre) VALUES ('Cuidado de animales');
INSERT INTO pasatiempos (nombre) VALUES ('Jugar a los bolos');
INSERT INTO pasatiempos (nombre) VALUES ('Pintar');
INSERT INTO pasatiempos (nombre) VALUES ('Ir a correr');
INSERT INTO pasatiempos (nombre) VALUES ('Bailar');
INSERT INTO pasatiempos (nombre) VALUES ('Montar a caballo');
INSERT INTO pasatiempos (nombre) VALUES ('Jugar al tennis');
INSERT INTO pasatiempos (nombre) VALUES ('Ir al teatro');
INSERT INTO pasatiempos (nombre) VALUES ('Jugar al billar');
INSERT INTO pasatiempos (nombre) VALUES ('Ir a la playa');
INSERT INTO pasatiempos (nombre) VALUES ('Trabajar como voluntario');